spring:
  application:
    name: my-hot-reconnect

server:
  port: 8081

apollo:
  bootstrap:
    enabled: true
  meta: http://localhost:8080
  #数据源
#  datasource:
#    name:
#     url: ${datasource.${spring.application.name}.url}&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#     username: ${datasource.${spring.application.name}.username}
#     password: ${datasource.${spring.application.name}.password}
#    url: jdbc:mysql://localhost:3306/my_hot_reconnect_1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 30
#      max-wait: 60000
#      time-between-eviction-runs-millis: 3000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select 1
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      connection-error-retry-attempts: 3
#      break-after-acquire-failure: false
#      time-between-connect-error-millis: 300000
#      stat-view-servlet:
#        url-pattern: /druid/*
#        login-username: openclass_user
#        login-password: openclass_user
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 2000
#      filters: stat,slf4j
